POST http://localhost:8081/test2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="ab.zip"
Content-Type: application/zip

< ab.zip
--WebAppBoundary--
###
GET http://10.1.98.240:8080/interface/Entrance.jsp?otherPageUrlString=dXNlcm5hbWU9MTEmcGFzc3dvcmQ9MTEmbG9naW50eXBlX3N5c3BhcmFtPTEmaWQ9dGVzdCZvcGVyYXRpb25UeXBlPXRlc3Q=&operationType=test&username=11&password=11&logintype_sysparam=1&id=test&operationType=test
