spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    timeout: 1H
#  banner:
#    image:
#      location: classpath:banner.png
test:
  schedule:
    delay: 9000

my:
  test:
    name: 小明
  test1:
    age: 17
